/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TafsirRouteImport } from './routes/tafsir'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MushafRouteImport } from './routes/mushaf'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as AdiyaRouteImport } from './routes/adiya'
import { Route as IndexRouteImport } from './routes/index'

const TafsirRoute = TafsirRouteImport.update({
  id: '/tafsir',
  path: '/tafsir',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MushafRoute = MushafRouteImport.update({
  id: '/mushaf',
  path: '/mushaf',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdiyaRoute = AdiyaRouteImport.update({
  id: '/adiya',
  path: '/adiya',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adiya': typeof AdiyaRoute
  '/audio': typeof AudioRoute
  '/mushaf': typeof MushafRoute
  '/search': typeof SearchRoute
  '/tafsir': typeof TafsirRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adiya': typeof AdiyaRoute
  '/audio': typeof AudioRoute
  '/mushaf': typeof MushafRoute
  '/search': typeof SearchRoute
  '/tafsir': typeof TafsirRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adiya': typeof AdiyaRoute
  '/audio': typeof AudioRoute
  '/mushaf': typeof MushafRoute
  '/search': typeof SearchRoute
  '/tafsir': typeof TafsirRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adiya' | '/audio' | '/mushaf' | '/search' | '/tafsir'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adiya' | '/audio' | '/mushaf' | '/search' | '/tafsir'
  id: '__root__' | '/' | '/adiya' | '/audio' | '/mushaf' | '/search' | '/tafsir'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdiyaRoute: typeof AdiyaRoute
  AudioRoute: typeof AudioRoute
  MushafRoute: typeof MushafRoute
  SearchRoute: typeof SearchRoute
  TafsirRoute: typeof TafsirRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tafsir': {
      id: '/tafsir'
      path: '/tafsir'
      fullPath: '/tafsir'
      preLoaderRoute: typeof TafsirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mushaf': {
      id: '/mushaf'
      path: '/mushaf'
      fullPath: '/mushaf'
      preLoaderRoute: typeof MushafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adiya': {
      id: '/adiya'
      path: '/adiya'
      fullPath: '/adiya'
      preLoaderRoute: typeof AdiyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdiyaRoute: AdiyaRoute,
  AudioRoute: AudioRoute,
  MushafRoute: MushafRoute,
  SearchRoute: SearchRoute,
  TafsirRoute: TafsirRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
